#!/bin/bash
#
# dewr is a development wrapper
# usage: 
#     > dewr build
#     > dewr run sh

DOCKERFILE="Dockerfile.dev"

export IMAGE_TAG=$(echo ${PWD//\//''} | awk '{print tolower($0)}')

if [[ $1 == "run" ]]; then
    docker run                       \
         --rm                        \
         --volume $(pwd):/opt/app    \
         --privileged                \
         -it $IMAGE_TAG              \
         $2
elif [[ $1 ==  "build" ]]; then 
    docker build -f Dockerfile.dev   \
      -t  "$IMAGE_TAG:latest"        \
      .
elif [[ $1 == "bash" ]]; then
    dewr run bash
else
  echo "I can only run or build things"
fi
